package com.constants;

import org.json.JSONArray;
import org.json.JSONException;

public class StateList {

    public static String stateList = "[\n" +
            "{\n" +
            "\"StateName\":\"ALABAMA\",\n" +
            "\"StateCode\":\"AL\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"ALBERTA\",\n" +
            "\"StateCode\":\"AB\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"ARIZONA\",\n" +
            "\"StateCode\":\"AZ\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"ARKANSAS\",\n" +
            "\"StateCode\":\"AR\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"BRITISH COLUMBIA\",\n" +
            "\"StateCode\":\"BC\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"CALIFORNIA\",\n" +
            "\"StateCode\":\"CA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"COLORADO\",\n" +
            "\"StateCode\":\"CO\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"CONNECTICUT\",\n" +
            "\"StateCode\":\"CT\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"DELAWARE\",\n" +
            "\"StateCode\":\"DE\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"DISTRICT OF COLUMBIA\",\n" +
            "\"StateCode\":\"DC\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"FLORIDA\",\n" +
            "\"StateCode\":\"FL\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"GEORGIA\",\n" +
            "\"StateCode\":\"GA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"IDAHO\",\n" +
            "\"StateCode\":\"ID\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"ILLINOIS\",\n" +
            "\"StateCode\":\"IL\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"INDIANA\",\n" +
            "\"StateCode\":\"IN\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"IOWA\",\n" +
            "\"StateCode\":\"IA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"KANSAS\",\n" +
            "\"StateCode\":\"KS\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"KENTUCKY\",\n" +
            "\"StateCode\":\"KY\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"LOUISIANA\",\n" +
            "\"StateCode\":\"LA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MAINE\",\n" +
            "\"StateCode\":\"ME\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MANITOBA\",\n" +
            "\"StateCode\":\"MB\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MARYLAND\",\n" +
            "\"StateCode\":\"MD\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MASSACHUSETTS\",\n" +
            "\"StateCode\":\"MA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MICHIGAN\",\n" +
            "\"StateCode\":\"MI\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MINNESOTA\",\n" +
            "\"StateCode\":\"MN\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MISSISSIPPI\",\n" +
            "\"StateCode\":\"MS\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MISSOURI\",\n" +
            "\"StateCode\":\"MO\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MONTANA\",\n" +
            "\"StateCode\":\"MT\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEBRASKA\",\n" +
            "\"StateCode\":\"NE\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEVADA\",\n" +
            "\"StateCode\":\"NV\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEWFOUNDLAND AND LABRADOR\",\n" +
            "\"StateCode\":\"NL\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEW BRUNSWICK\",\n" +
            "\"StateCode\":\"NB\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEW HAMPSHIRE\",\n" +
            "\"StateCode\":\"NH\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEW JERSEY\",\n" +
            "\"StateCode\":\"NJ\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEW MEXICO\",\n" +
            "\"StateCode\":\"NM\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NEW YORK\",\n" +
            "\"StateCode\":\"NY\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NORTH CAROLINA\",\n" +
            "\"StateCode\":\"NC\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NORTH DAKOTA\",\n" +
            "\"StateCode\":\"ND\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NORTHWEST TERRITORIES\",\n" +
            "\"StateCode\":\"NT\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"NOVA SCOTIA\",\n" +
            "\"StateCode\":\"NS\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"OHIO\",\n" +
            "\"StateCode\":\"OH\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"OKLAHOMA\",\n" +
            "\"StateCode\":\"OK\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"ONTARIO\",\n" +
            "\"StateCode\":\"ON\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"OREGON\",\n" +
            "\"StateCode\":\"OR\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"PENNSYLVANIA\",\n" +
            "\"StateCode\":\"PA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"PRINCE EDWARD ISLAND\",\n" +
            "\"StateCode\":\"PE\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"QUEBEC\",\n" +
            "\"StateCode\":\"QC\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"RHODE ISLAND\",\n" +
            "\"StateCode\":\"RI\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"SASKATCHEWAN\",\n" +
            "\"StateCode\":\"SK\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"SOUTH CAROLINA\",\n" +
            "\"StateCode\":\"SC\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"SOUTH DAKOTA\",\n" +
            "\"StateCode\":\"SD\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"TENNESSEE\",\n" +
            "\"StateCode\":\"TN\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"TEXAS\",\n" +
            "\"StateCode\":\"TX\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"UTAH\",\n" +
            "\"StateCode\":\"UT\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"VERMONT\",\n" +
            "\"StateCode\":\"VT\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"VIRGINIA\",\n" +
            "\"StateCode\":\"VA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"WASHINGTON\",\n" +
            "\"StateCode\":\"WA\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"WEST VIRGINIA\",\n" +
            "\"StateCode\":\"WV\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"WISCONSIN\",\n" +
            "\"StateCode\":\"WI\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"WYOMING\",\n" +
            "\"StateCode\":\"WY\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"YUKON\",\n" +
            "\"StateCode\":\"YT\",\n" +
            "\"Country\":\"CANADA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"HAWAII\",\n" +
            "\"StateCode\":\"HI\",\n" +
            "\"Country\":\"USA\"\n" +
            "},\n" +
            "{\n" +
            "\"StateName\":\"MEXICO\",\n" +
            "\"StateCode\":\"MEXICO\",\n" +
            "\"Country\":\"USA\"\n" +
            "}\n" +
            "]";

    public static JSONArray getStateArray() throws JSONException {
        return new JSONArray(stateList);
    }

}
